source 'https://rubygems.org'

gem 'sqlite3'
gem 'sequel'
gem 'sequel_secure_password'
gem 'rack', '1.5.2'
gem 'sinatra'
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
gem 'haml'
gem 'shotgun'
